name: check-atomic-commits

on: pull_request

jobs:
  atomic-commits:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Install git
      run: dnf install -y git
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Mark github workspace as safe
      run: git config --system --add safe.directory $PWD
    - name: List commits and run make for each
      run: |
        git rev-list --reverse ${{ github.event.pull_request.base.sha }}..HEAD | while read commit; do
          git checkout $commit
          make
        done
