name: Build and Checks

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        dnf copr enable @CESNET/NEMEA
        dnf install -y make gcc-c++ clang clang-tools-extra libtrap-devel unirec cmake3 git which rpm-build
    - name: make format-check
      run: make format
    - name: make tidy-check
      run: make tidy
    - name: make
      run: make

  editor-config:
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Check editorconfig
      run: ec --exclude .git