name: upload SRPM to copr

on:
  push:
    branches:
      - release

jobs:
  upload-srpm-to-copr:
    runs-on: ubuntu-latest
    container: oraclelinux:9
    steps:
    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Mark github workspace as safe
      run: git config --system --add safe.directory $PWD
    - name: make rpm
      run: make rpm
    - name: Create copr config
      run: |
        mkdir ~/.config
        echo "${{ secrets.COPR_CONFIG }}" >> ~/.config/copr
    - name: Upload SRPM to copr
      run: |
        copr build @CESNET/NEMEA build/pkg/rpm/rpmbuild/SRPMS/*
        copr build @CESNET/NEMEA-testing build/pkg/rpm/rpmbuild/SRPMS/*

