name: test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    container: ${{ inputs.os }}
    steps:
    - name: Install dependencies
      run: |
        dnf install -y dnf-plugins-core
        dnf -y copr enable @CESNET/NEMEA
    - name: extract artifact name
      run: |
        OS=${{ inputs.os }}
        echo "artifactName=$(echo ${OS/:/}-rpm)" >> $GITHUB_ENV
    - name: download RPM artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.artifactName }}
    - name: install RPM artifact
      run: |
        dnf install -y *.rpm
