name: upload

on:
  push:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^Merge pull request #\d+ from .*/new_version$'i
