name: upload

on:
  push:
    branches:
      - main

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run your command
      run: |
        echo "${{ github.event.head_commit.message }}"
        echo "${{ github.event.workflow_run.head_commit.message }}"      
        echo "Run your command here"
