name: upload

on:
  push:

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^Merge pull request #\d+ from .*/new_version$'i
      - name: Upload SRPM to copr
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          echo "Regex match'
